### ISSUE TITLE
请问乱码的问题应当如何解决？

### ISSUE THREAD

**Issue by Sciroccogti** [gorquan/QQMusic#1]
如下图所示。我根据网传教程进行了字体替换但是似乎不起作用，期望能在此获得一些建议和帮助。谢谢！

![图片](https://user-images.githubusercontent.com/32357397/73594671-6bb35500-454b-11ea-8f86-c8ad52587670.png)

测试环境：Ubuntu 18.04 LTS

**Comment by gorquan** [comment]
你的应该是中文字符的Ubuntu吧，我建议你这种情况下还是用我另外一个仓库的deepin-wine-docker，这个乱码问题是因为语言符号及其分类(LC_CTYPE)的问题导致的.
这是我研究docker封装时做的一个测试
`乱码locale
        LANG=
        LANGUAGE=
        LC_CTYPE=zh_CN.UTF-8
        LC_NUMERIC="POSIX"
        LC_TIME="POSIX"
        LC_COLLATE="POSIX"
        LC_MONETARY="POSIX"
        LC_MESSAGES="POSIX"
        LC_PAPER="POSIX"
        LC_NAME="POSIX"
        LC_ADDRESS="POSIX"
        LC_TELEPHONE="POSIX"
        LC_MEASUREMENT="POSIX"
        LC_IDENTIFICATION="POSIX"
        LC_ALL=`
`正常locale
        LANG=
        LANGUAGE=
        LC_CTYPE=en_US.UTF-8
        LC_NUMERIC="POSIX"
        LC_TIME="POSIX"
        LC_COLLATE="POSIX"
        LC_MONETARY="POSIX"
        LC_MESSAGES="POSIX"
        LC_PAPER="POSIX"
        LC_NAME="POSIX"
        LC_ADDRESS="POSIX"
        LC_TELEPHONE="POSIX"
        LC_MEASUREMENT="POSIX"
        LC_IDENTIFICATION="POSIX"
        LC_ALL=`
在docker中，我把LC_CTYPE=zh_CN.UTF-8改为LC_CTYPE=en_US.UTF-8解决了乱码的问题，真实环境中没有机子我就没有测试了。不过有的网友在deepin测试后说系统会乱码，你斟酌一下。
还有，这个源码是比较旧版本的，我还没时间更新，后面会进行更新。如果比较急想用新版本的，可以参考一下我仓库进行封装。

**Comment by gorquan** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=181461&extra=

**Comment by Sciroccogti** [comment]
非常感谢，目前使用体验极佳！

![图片](https://user-images.githubusercontent.com/32357397/73734402-8cacbd80-4778-11ea-97a6-8d78996d5e0c.png)

**Comment by Sciroccogti** [comment]
事实上，直接修改`/etc/default/locale`中的`LC_CTYPE`为`en_US.UTF-8`后，新的乱码出现了：

![图片](https://user-images.githubusercontent.com/32357397/73738283-2ecfa400-477f-11ea-9d87-01ff705d7a44.png)

其它界面倒没乱码

**Comment by gorquan** [comment]
> 事实上，直接修改`/etc/default/locale`中的`LC_CTYPE`为`en_US.UTF-8`后，新的乱码出现了：
> 
> ![图片](https://user-images.githubusercontent.com/32357397/73738283-2ecfa400-477f-11ea-9d87-01ff705d7a44.png)
> 
> 其它界面倒没乱码

这个是docker里面还是宿主机里面？

**Comment by gorquan** [comment]
> 非常感谢，改用了[deepin-wine-docker](https://github.com/gorquan/deepin-wine-docker)，目前使用体验极佳！
> 
> ![图片](https://user-images.githubusercontent.com/32357397/73734402-8cacbd80-4778-11ea-97a6-8d78996d5e0c.png)

好用就欢迎留个star哈~有好的建议或者代码有问题的地方可以提个issue和pr~

**Comment by Sciroccogti** [comment]
> 这个是docker里面还是宿主机里面？
是宿主机的，也就是目前这个repo的软件 ~~现在才发现忘了回复了QAQ~~

**Comment by Sciroccogti** [comment]
我感觉是语言符号改过头了（

然而我到现在也没有试出合适的配置
