### ISSUE TITLE
deepin下乱码解决方案

### ISSUE THREAD

**Issue by wyy0117** [gorquan/QQMusic#2]
论坛上有位大佬搞定了，参考：https://qzone.work/technologys/307.html，希望可以重新打包

**Comment by gorquan** [comment]
感谢，因为在ubuntu中是没有乱码的，所以我会另外重新开一个仓库重新打包上传

**Comment by wyy0117** [comment]
谢谢，辛苦了。

**Comment by gorquan** [comment]
已经重新打包了，暂时没有在deepin上面进行测试，后续有空测试发现问题欢迎反馈

**Comment by Sciroccogti** [comment]
重新打包后可以显示符号了，但是中文不能显示，提示 simsun 什么的（中文显示有问题所以认不出

不过手动安装了simsun.ttc以后就OK了！

**Comment by gorquan** [comment]
> 重新打包后可以显示符号了，但是中文不能显示，提示 simsun 什么的（中文显示有问题所以认不出
> 
> 不过手动安装了simsun.ttc以后就OK了！

那个是宋体字体缺失问题，我在包里面加了simsun.ttc，怕是没生效
