### ISSUE TITLE
客户端自动升级导致无法启动

### ISSUE THREAD

**Issue by wyy0117** [gorquan/QQMusic#3]
使用run.sh启动时会报QQMusic.exe找不到，跟踪到路径下确实找不到，exe被放到QQMusic1752.17.43.10文件夹下了，坑爹的tx，手动移动到上级文件夹下搞定。

**Comment by gorquan** [comment]
感谢反馈

**Comment by Sciroccogti** [comment]
在Ubuntu18.04似乎能够正常更新。

我今天遇到了无法启动的情况，以为也是更新所致。但是经过删除配置文件并重装的操作后，能够正常使用，并且手动进行更新后也能开启。

作者等有空了可以重新打个包啦2333

**Comment by dafeinayius** [comment]
遇到了@wyy0117一样的问题，但手动移到上级目录后，出现了无法记住密码的现象，每次打开都要重新登录。

**Comment by gorquan** [comment]
已经更新了17.66，欢迎大家测试 @dafeinayius  @Sciroccogti  @wyy0117
