### ISSUE TITLE
听歌过程中闪退

### ISSUE THREAD

**Issue by dengzhenli** [gorquan/QQMusic#4]
有时候听着听着就程序就退出了,不知道是什么原因

**Comment by gorquan** [comment]
时间长吗，程序过长时间会出现不稳定，现在这个版本应该不会存在点击歌单闪退的问题了

**Comment by gorquan** [comment]
我周末打包一个新的版本，你再试试

**Comment by dengzhenli** [comment]
确实是听久了才会,因为我一般一听就是一天.最近这段时间留意下

**Comment by dengzhenli** [comment]
确实是听久了才会,因为我一般一听就是一天.最近这段时间留意下

**Comment by dengzhenli** [comment]
确实是听久了才会,因为我一般一听就是一天.最近这段时间留意下

**Comment by dengzhenli** [comment]
确实是听久了才会,因为我一般一听就是一天.最近这段时间留意下

**Comment by dengzhenli** [comment]
确实是听久了才会,因为我一般一听就是一天.最近这段时间留意下

**Comment by dengzhenli** [comment]
确实是听久了才会,因为我一般一听就是一天.最近这段时间留意下

**Comment by dengzhenli** [comment]
确实是听久了才会,因为我一般一听就是一天.最近这段时间留意下

**Comment by dengzhenli** [comment]
确实是听久了才会,因为我一般一听就是一天.最近这段时间留意下

**Comment by dengzhenli** [comment]
![2020-08-19 11-03-44屏幕截图](https://user-images.githubusercontent.com/12746883/90588402-1bad8e80-e20e-11ea-8fc9-060073f00f75.png)
听了两个小时后出现了,是在切歌的时候

**Comment by gorquan** [comment]
> ![2020-08-19 11-03-44屏幕截图](https://user-images.githubusercontent.com/12746883/90588402-1bad8e80-e20e-11ea-8fc9-060073f00f75.png)
> 听了两个小时后出现了,是在切歌的时候

下个版本我修复一下吧

**Comment by gorquan** [comment]
> ![2020-08-19 11-03-44屏幕截图](https://user-images.githubusercontent.com/12746883/90588402-1bad8e80-e20e-11ea-8fc9-060073f00f75.png)
> 听了两个小时后出现了,是在切歌的时候

不要指望他很稳定，毕竟wine跑起来的，并不会稳定

**Comment by dengzhenli** [comment]
我想我找到原因了,部分歌曲没版权会自动跳mv,打开mv就会奔溃.设置里面关掉自动切换mv就行了
